---
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    restart: always
    build:
      dockerfile: ../build/Dockerfile
      context: ../golang_server/
      target: dev
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WEB_PORT=${WEB_PORT}
    links:
      - db
    volumes:
      - '../golang_server:/opt/app/api'
volumes:
  db:
    driver: local
